import Footer from './components/Footer.js';
import Navigation from './components/Navigation.js';
import ScrollButton from './components/ScrollButton.js';
import './globals.css'

export const metadata = {
  title: 'Proyecto Verdeo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex flex-col h-screen bg-amber-50'>
        <Navigation />
        <ScrollButton />
        {children}
        <Footer />
      </body>
    </html>
  )
}
